version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: flauc/firebase
    environment:
      NPM_VERSION: "6.9.0"
    steps:
      - checkout
      - run:
          name: Set Public Environment
          command: echo export const ENV_CONFIG=$PUBLIC_CONFIG > env-config.js
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Install Shared dependencies
          command: yes | npm ci || true
      - run:
          name: Install Function dependencies
          command: yes | npm --prefix functions ci || true
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: Set Firebase Environment
          command: npm run target-setup -- --token $FIREBASE_CI_TOKEN --project genos-glyco
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - package.json
            - package-lock.json
            - firebase.json
            - __sapper__
            - functions
            - static
            - .firebaserc
  deploy:
    docker:
      - image: flauc/firebase
    working_directory: ~/project
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy  -- -m $CIRCLE_SHA1 --token $FIREBASE_CI_TOKEN --project genos-glyco
workflows:
  version: 2
  -deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
